name: Build and Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Options include: 'zulu', 'adopt', 'adopt-hotspot', 'adopt-openj9', 'amazon', 'liberica', 'microsoft', 'temurin', 'oracle', 'oracle-openj9'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: docker build . -t my-spring-boot-app:latest

    - name: Save Docker image to tar
      run: docker save my-spring-boot-app:latest -o my-spring-boot-app.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-spring-boot-app
        path: my-spring-boot-app.tar

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: my-spring-boot-app
        path: my-spring-boot-app.tar

    - name: Load Docker image
      run: docker load -i my-spring-boot-app.tar

    - name: Run Docker container
      run: docker run -d -p 8080:8080 my-spring-boot-app:latest
