name: Deploy Spring Boot App

on:
  push:
    branches:
      - main  # Adjust to your main branch name
      - development  # Add other branches as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Build Docker image
        run: docker build -t spring-boot-app .

      - name: Deploy to Docker
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/student_db?createDatabaseIfNotExists=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          SPRING_JPA_SHOW_SQL: true
          SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: |
          docker-compose up -d --build
