name: Build and Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./student-crud-app-1

    - name: Build Docker image
      run: docker-compose build
      working-directory: ./student-crud-app-1

    - name: Save Docker images to tar
      run: |
        docker save -o spring-boot-app.tar spring-boot-app
        docker save -o mysql.tar mysql:8.0
      working-directory: ./student-crud-app-1

    - name: Upload Docker images artifacts
      uses: actions/upload-artifact@v2
      with:
        name: docker-images
        path: |
          ./student-crud-app-1/spring-boot-app.tar
          ./student-crud-app-1/mysql.tar

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Docker images artifacts
      uses: actions/download-artifact@v2
      with:
        name: docker-images
        path: .

    - name: Load Docker images
      run: |
        docker load -i spring-boot-app.tar
        docker load -i mysql.tar

    - name: Run Docker Compose
      run: docker-compose up -d
      working-directory: ./student-crud-app-1
