name: Build and Deploy to Local

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_DATABASE: your_database_name
          MYSQL_USER: your_username
          MYSQL_PASSWORD: your_password
          MYSQL_ROOT_PASSWORD: root_password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./student-crud-app-1

    - name: Build Docker image
      run: docker build . -t my-spring-boot-app:latest
      working-directory: ./student-crud-app-1

    - name: Save Docker image to tar
      run: docker save my-spring-boot-app:latest -o my-spring-boot-app.tar
      working-directory: ./student-crud-app-1

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-spring-boot-app
        path: ./student-crud-app-1/my-spring-boot-app.tar

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: my-spring-boot-app
        path: my-spring-boot-app.tar

    - name: Load Docker image
      run: docker load -i my-spring-boot-app.tar

    - name: Run Docker container
      run: docker run -d -p 8080:8080 my-spring-boot-app:latest
